name: Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, develop]

    steps:
      - uses: actions/checkout@v2
      - name: Branch
        id: get-branch
        run: |
          echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        
      - name: Print branch
        run: |
          echo ${{ steps.get-branch.outputs.branch }}
          echo ${{ github.event.action }}
