name: Jekyll site CI

on:
  schedule:
    cron: */5 * * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Branch
      run: |
        echo ${GITHUB_REF#refs/heads/}
